[project]
name = "2lab"
version = "7.7.7"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.6.2",
    "aiosmtplib>=5.1.0",
    "aiosqlite>=0.22.1",
    "fastapi>=0.135.1",
    "httpx>=0.28.1",
    "minio>=7.2.20",
    "mongoengine>=0.29.3",
    "pydantic[email]>=2.12.5",
    "pyjwt>=2.12.1",
    "python-multipart>=0.0.29",
    "redis>=7.4.0",
    "sqlalchemy>=2.0.48",
    "uvicorn>=0.41.0",
]
