alias fm := fast_migrations
alias b := build
alias u := up
alias d := down
alias t := test

build:
    docker compose up --build -d

up:
    docker compose up -d

down:
    docker compose down -v
    rm -f migrations/versions/*.py

fast_migrations:
    just makemigrations foo
    just migrate
    sleep 2
    just test

# Создать новую миграцию. Example: "foo"
makemigrations msg:
    docker compose exec app uv run alembic revision --autogenerate -m "{{ msg }}"

# Миграция
migrate:
    docker compose exec app uv run alembic upgrade head

logs:
    docker logs wp_labs_app

test:
    curl -X POST http://localhost:4200/tasks \
          -H "Content-Type: application/json" \
          -d '{"title": "FooBar", "status": "todo"}'
    curl "http://localhost:4200/tasks?page=1&limit=10"
